# Generated by Django 5.1.2 on 2025-01-26 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='univs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('img', models.URLField()),
                ('location', models.CharField(max_length=100)),
                ('acceptance', models.CharField(max_length=100)),
                ('gre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ranks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=15)),
                ('topic', models.CharField(max_length=15)),
                ('score', models.FloatField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='univ.univs')),
            ],
        ),
    ]
