# Generated by Django 5.1.2 on 2025-01-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='')),
                ('des', models.TextField()),
                ('link', models.URLField(unique=True)),
                ('words', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
