# Generated by Django 5.1.2 on 2025-01-19 16:55

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogs_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='img',
            field=models.ImageField(null=True, storage=blogs.models.TableBasedStorage(table_name='blogs'), upload_to=''),
        ),
    ]
