# Generated by Django 5.1.2 on 2025-01-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogs_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='link',
            field=models.URLField(),
        ),
    ]
